
export const ADD_TO_CART  = "ADD_TO_CART";
export const ADD_PRODUCT_DATA  = "ADD_PRODUCT_DATA";
export const REMOVE_PRODUCT_DATA = "REMOVE_PRODUCT_DATA"
export const MODIFY_PRODUCT_DATA = "MODIFY_PRODUCT_DATA"
export const SUBMIT_MODIFY_DATA = "SUBMIT_MODIFY_DATA"
export const ADD_TO_ORDERED = "ADD_TO_ORDERED"